services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    restart: "unless-stopped"
    ports:
      - "${POSTGRES_EXPORT_PORT}:5432"
    networks:
      - project
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER" ]
      timeout: 45s
      interval: 10s
      retries: 10

  avito-shop-service:
    build:
      context: .
      dockerfile: ./build/package/Dockerfile
    container_name: avito-shop-service
    env_file:
      - .env
    restart: "unless-stopped"
    links:
      - postgres
    ports:
      - "${PROJECT_EXPORT_PORT}:8080"
      - "${STATUS_EXPORT_PORT}:8075"
    depends_on:
      - postgres
    networks:
      - project
    healthcheck:
      test: [ 'CMD', 'curl', 'http://localhost:8075/live' ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  project:
    driver: bridge

#TODO: проверить, что он сходиться с тем, что в примере